import AgentDeckCore
import AppKit
import XCTest

@testable import AgentDeck

/// 把“有数据”的界面渲染成 PNG（/tmp），供人工核对真实呈现。
/// 会话数据经 canonical Runtime v2 catalog + snapshot barrier 注入，无需真 daemon。
@MainActor
final class RenderSnapshotTests: XCTestCase {
  func testRenderHeader() throws {
    let model = try canonicalModel(
      items: [
        snapshotItem(
          "item-user-header",
          commandID: "command-header",
          item: .userMessage(
            text: "把登录模块拆分为独立 service，抽出 token 刷新逻辑，并补齐单元测试。",
            meta: RuntimeAgentItemMetaV1()
          )
        )
      ]
    )
    let header = CodexContentHeaderView(model: model)
    header.wantsLayer = true
    header.frame = NSRect(x: 0, y: 0, width: 1100, height: 44)
    header.layoutSubtreeIfNeeded()
    header.renderPNG(to: "/tmp/adk-header.png")
  }

  func testRenderComposer() {
    let model = SessionModel()
    model.cwd = URL(fileURLWithPath: "/p/refactor-auth")
    let bar = InputBarView(model: model)
    bar.wantsLayer = true
    bar.layer?.backgroundColor = DesignTokens.bg.cgColor
    bar.frame = NSRect(x: 0, y: 0, width: 720, height: 96)
    bar.layoutSubtreeIfNeeded()
    bar.renderPNG(to: "/tmp/adk-composer.png")
  }

  func testRenderToolCallCollapsed() throws {
    let model = try canonicalModel(items: [toolCallItem(id: "item-tool-collapsed")])
    let item = try XCTUnwrap(model.selectedItems.first)
    let row = ConversationDisplayRow(
      role: .assistantItem,
      turnId: "turn-render",
      item: item,
      firstInTurn: true,
      lastInTurn: true
    )
    let cell = ToolCallCellView()
    cell.wantsLayer = true
    cell.layer?.backgroundColor = DesignTokens.bg.cgColor
    let width: CGFloat = 620
    let height = ConversationRowFactory.height(for: row, width: width) + 6
    cell.translatesAutoresizingMaskIntoConstraints = false
    cell.widthAnchor.constraint(equalToConstant: width).isActive = true
    cell.heightAnchor.constraint(equalToConstant: height).isActive = true
    cell.configure(row: row, width: width, model: model)
    cell.layoutSubtreeIfNeeded()
    cell.renderPNG(to: "/tmp/adk-toolcall.png")
  }

  func testRenderToolCallExpanded() throws {
    final class AlwaysExpanded: ConversationDisclosureStateStore {
      func isItemExpanded(_ itemId: String) -> Bool { true }
      func setItem(_ itemId: String, expanded: Bool) {}
    }

    let model = try canonicalModel(items: [toolCallItem(id: "item-tool-expanded")])
    let item = try XCTUnwrap(model.selectedItems.first)
    let row = ConversationDisplayRow(
      role: .assistantItem,
      turnId: "turn-render",
      item: item,
      firstInTurn: true,
      lastInTurn: true
    )
    let store = AlwaysExpanded()
    let cell = ToolCallCellView()
    cell.disclosureStore = store
    cell.wantsLayer = true
    cell.layer?.backgroundColor = DesignTokens.bg.cgColor
    cell.translatesAutoresizingMaskIntoConstraints = false
    cell.widthAnchor.constraint(equalToConstant: 620).isActive = true
    cell.heightAnchor.constraint(equalToConstant: 220).isActive = true
    cell.configure(row: row, width: 620, model: model)
    cell.layoutSubtreeIfNeeded()
    cell.renderPNG(to: "/tmp/adk-toolcall-expanded.png")
  }

  func testRenderConversationStream() throws {
    let model = try canonicalModel(
      items: [
        // CLI 命令元数据噪声（应被过滤，不出现在流里）
        snapshotItem(
          "item-command-caveat",
          commandID: "command-caveat",
          item: .userMessage(
            text:
              "<local-command-caveat>Caveat: messages below were generated by local commands. DO NOT respond…</local-command-caveat>",
            meta: RuntimeAgentItemMetaV1()
          )
        ),
        snapshotItem(
          "item-command-clear",
          commandID: "command-clear",
          item: .userMessage(
            text:
              "<command-name>/clear</command-name><command-message>clear</command-message><command-args></command-args>",
            meta: RuntimeAgentItemMetaV1()
          )
        ),
        snapshotItem(
          "item-user-stream",
          commandID: "command-stream",
          item: .userMessage(
            text: "把登录模块拆分成独立的 auth service，抽出 token 刷新逻辑，并补齐单元测试。",
            meta: RuntimeAgentItemMetaV1()
          )
        ),
        snapshotItem(
          "item-reasoning-stream",
          commandID: "command-stream",
          item: .reasoning(
            text: "先梳理 auth 目录下的依赖关系，确认哪些函数被外部引用，再决定拆分边界。",
            meta: RuntimeAgentItemMetaV1()
          )
        ),
        snapshotItem(
          "item-assistant-stream",
          commandID: "command-stream",
          item: .assistantMessage(
            text: "我会先分析依赖，再抽出 service，最后补测试。",
            meta: RuntimeAgentItemMetaV1()
          )
        ),
        toolCallItem(id: "item-tool-stream", commandID: "command-stream"),
      ]
    )

    let vc = ConversationViewController(model: model)
    let view = vc.view
    view.frame = NSRect(x: 0, y: 0, width: 900, height: 640)
    view.layoutSubtreeIfNeeded()
    view.renderPNG(to: "/tmp/adk-stream.png")
  }

  func testRenderFullSessionWindow() throws {
    let model = try canonicalModel(
      items: [
        snapshotItem(
          "item-user-session",
          commandID: "command-session",
          item: .userMessage(
            text: "把登录模块拆分成独立的 auth service，抽出 token 刷新逻辑，并补齐单元测试。",
            meta: RuntimeAgentItemMetaV1()
          )
        ),
        snapshotItem(
          "item-assistant-session",
          commandID: "command-session",
          item: .assistantMessage(
            text: "已梳理 auth 依赖并完成服务拆分，下一步运行 focused tests。",
            meta: RuntimeAgentItemMetaV1()
          )
        ),
      ]
    )
    _ = model.shouldAutoRefreshHistoryOnAppear()

    let vc = SessionViewController(model: model)
    let view = vc.view
    view.frame = NSRect(x: 0, y: 0, width: 1280, height: 760)
    view.layoutSubtreeIfNeeded()
    view.renderPNG(to: "/tmp/adk-session.png")
  }

  private func canonicalModel(
    conversationID: RuntimeConversationID = RuntimeConversationID(
      rawValue: "conversation-render"
    ),
    cwd: String = "/p/refactor-auth",
    items: [SnapshotItemV1]
  ) throws -> SessionModel {
    let model = SessionModel()
    model.cwd = URL(fileURLWithPath: cwd)
    try model.workbench.installCatalog(
      snapshotPages: [
        try RuntimeCatalogSnapshotV2(
          baseCatalogCursor: .beforeFirst,
          entries: [
            RuntimeConversationEntryV2(
              conversationID: conversationID,
              agentKind: .codex,
              title: "Refactor auth",
              cwd: cwd,
              lastActiveMs: 1_000,
              archived: false,
              entryRevision: 1
            )
          ],
          nextPageCursor: nil
        )
      ]
    )
    let snapshot = try ConversationSnapshotV2(
      conversationID: conversationID,
      baseEventCursor: .beforeFirst,
      configurationState: try RuntimeConversationConfigurationStateV2(
        configurationRevision: 0,
        configuration: nil
      ),
      items: [.capabilities(try capabilities())] + items
    )
    _ = try model.workbench.ingest(.synchronizedReply(.snapshot(snapshot)))
    _ = try model.workbench.ingest(
      .synchronizedReply(
        .syncComplete(try syncComplete(conversationID: conversationID))
      )
    )
    try model.workbench.selectConversation(conversationID)
    return model
  }

  private func snapshotItem(
    _ id: String,
    commandID: String?,
    item: RuntimeAgentItemV1
  ) -> SnapshotItemV1 {
    .item(
      itemID: RuntimeItemID(rawValue: id),
      entityID: RuntimeEntityID(rawValue: "entity-\(id)"),
      commandID: commandID.map(RuntimeCommandID.init(rawValue:)),
      item: item
    )
  }

  private func toolCallItem(
    id: String,
    commandID: String = "command-tool"
  ) -> SnapshotItemV1 {
    snapshotItem(
      id,
      commandID: commandID,
      item: .toolCall(
        name: "TaskCreate",
        args: AnyCodable([
          "activeForm": "收录厂家摄像头资料",
          "subject": "收录厂家参数",
          "description": "把资料收进当前仓库",
        ]),
        result: AnyCodable(["status": "completed"]),
        meta: RuntimeAgentItemMetaV1()
      )
    )
  }

  private func capabilities() throws -> RuntimeSessionCapabilitiesV1 {
    try decode(
      RuntimeSessionCapabilitiesV1.self,
      [
        "agentKind": "codex",
        "agentVersion": "test",
        "features": ["streamingMessages", "streamingReasoning"],
        "vendor": [
          "agentKind": "codex",
          "sandboxModes": ["workspace-write"],
          "persistenceSupported": false,
          "reasoningEffortLevels": ["medium"],
        ],
      ]
    )
  }

  private func syncComplete(
    conversationID: RuntimeConversationID
  ) throws -> RuntimeSyncCompleteV1 {
    try decode(
      RuntimeSyncCompleteV1.self,
      [
        "streamGeneration": "fixture-generation",
        "streamCursor": "beforeFirst",
        "innerCursor": [
          "scope": "conversation",
          "conversationId": conversationID.rawValue,
          "cursor": "beforeFirst",
        ],
        "keyDirectoryRevision": 0,
      ]
    )
  }

  private func decode<Value: Decodable>(_ type: Value.Type, _ object: Any) throws -> Value {
    let data = try JSONSerialization.data(withJSONObject: object, options: [.sortedKeys])
    return try JSONDecoder().decode(type, from: data)
  }
}
