import XCTest
import AgentDeckMobileCore

final class CommandMessageSanitizerTests: XCTestCase {

    // MARK: 噪声整块隐藏

    func testCaveatOnlyMessageIsDropped() {
        let raw = "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond…</local-command-caveat>"
        XCTAssertNil(CommandMessageSanitizer.sanitize(userText: raw))
    }

    func testSlashCommandInvocationIsDropped() {
        let raw = "<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>"
        XCTAssertNil(CommandMessageSanitizer.sanitize(userText: raw))
    }

    func testCommandStdoutStderrBlocksAreDropped() {
        let raw = "<command-stdout>done</command-stdout><command-stderr></command-stderr>"
        XCTAssertNil(CommandMessageSanitizer.sanitize(userText: raw))
    }

    func testLocalCommandStdoutStderrBlocksAreDropped() {
        let raw = "<local-command-stdout>Set model to \u{1B}[1mFable 5\u{1B}[22m</local-command-stdout>"
            + "<local-command-stderr>warning</local-command-stderr>"
        XCTAssertNil(CommandMessageSanitizer.sanitize(userText: raw))
    }

    // MARK: 真实消息保留

    func testPlainUserMessageIsUnchanged() {
        let raw = "把登录模块拆分为独立 service，并补齐单元测试。"
        XCTAssertEqual(CommandMessageSanitizer.sanitize(userText: raw), raw)
    }

    func testRealProseWithStrayTagKeepsProse() {
        let raw = "<local-command-caveat>Caveat…</local-command-caveat>\n帮我点亮两颗摄像头并验证图像。"
        XCTAssertEqual(CommandMessageSanitizer.sanitize(userText: raw), "帮我点亮两颗摄像头并验证图像。")
    }

    // MARK: 展示用清洗

    func testCleanedForDisplayReturnsEmptyForNoise() {
        let raw = "<command-name>/clear</command-name>"
        XCTAssertEqual(CommandMessageSanitizer.cleanedForDisplay(raw), "")
    }

    // MARK: 对话流集成 —— 噪声轮次被丢弃

    func testConversationTurnsDropCommandNoise() {
        let turns = makeConversationTurns(from: [
            UIItem(id: "c1", lifecycle: "completed", kind: "user",
                   text: "<local-command-caveat>Caveat…</local-command-caveat>"),
            UIItem(id: "c2", lifecycle: "completed", kind: "user",
                   text: "<command-name>/clear</command-name><command-message>clear</command-message><command-args></command-args>"),
            UIItem(id: "c3", lifecycle: "completed", kind: "user",
                   text: "<local-command-stdout>Set model to Fable 5</local-command-stdout>"),
            UIItem(id: "u1", lifecycle: "completed", kind: "user", text: "真实问题：帮我收录资料"),
            UIItem(id: "m1", lifecycle: "completed", kind: "message", text: "好的，我先建任务清单。"),
        ])
        XCTAssertEqual(turns.count, 1, "三条命令噪声轮次应被丢弃，仅剩真实轮次")
        XCTAssertEqual(turns.first?.user?.id, "u1")
        XCTAssertEqual(turns.first?.user?.text, "真实问题：帮我收录资料")
        XCTAssertEqual(turns.first?.assistantItems.map(\.id), ["m1"])
    }

    // MARK: Tool call 载荷美化

    func testToolPayloadPrettyPrintsArguments() {
        var item = UIItem(id: "t1", lifecycle: "completed", kind: "toolCall")
        item.tool = "TaskCreate"
        item.arguments = "{\"activeForm\":\"收录厂家资料\",\"subject\":\"收录\"}"
        let payload = ToolPresentation.toolPayload(item)
        XCTAssertTrue(payload.hasPrefix("arguments\n"), "应带 arguments 前缀")
        XCTAssertTrue(payload.contains("\n  \""), "紧凑 JSON 应被缩进美化")
    }

    func testPrettyJSONFallsBackForNonJSON() {
        XCTAssertEqual(ToolPresentation.prettyJSON("just a string"), "just a string")
    }
}
